"""add indexes absent flag and unique constraint to grades

Revision ID: 1133e27a4f57
Revises: 0a54ae93d4ea
Create Date: 2026-05-04 23:46:54.937914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1133e27a4f57'
down_revision = '0a54ae93d4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('absent', sa.Boolean(), server_default='false', nullable=False))
        batch_op.drop_index(batch_op.f('idx_grades_academic_period_id'))
        batch_op.drop_index(batch_op.f('idx_grades_student_id'))
        batch_op.create_index(batch_op.f('ix_grades_academic_period_id'), ['academic_period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grades_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grades_subject_id'), ['subject_id'], unique=False)
        batch_op.create_unique_constraint('uq_grade_student_subject_period', ['student_id', 'subject_id', 'academic_period_id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_students_identification'))
        batch_op.create_index(batch_op.f('ix_students_major_id'), ['major_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_major_id'))
        batch_op.create_index(batch_op.f('idx_students_identification'), ['identification'], unique=False)

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('uq_grade_student_subject_period', type_='unique')
        batch_op.drop_index(batch_op.f('ix_grades_subject_id'))
        batch_op.drop_index(batch_op.f('ix_grades_student_id'))
        batch_op.drop_index(batch_op.f('ix_grades_academic_period_id'))
        batch_op.create_index(batch_op.f('idx_grades_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_grades_academic_period_id'), ['academic_period_id'], unique=False)
        batch_op.drop_column('absent')

    # ### end Alembic commands ###
